### ISSUE TITLE
Feature Request: forward data via MQTT

### ISSUE THREAD

**Issue by knowthelist** [aaronjbrown/PyGrowatt#2] opened 2021-03-20 11:14 UTC
Could you add the option to forward data via MQTT (for home automation), as an alternative to Pvoutput?

**Comment by aaronjbrown** [comment] 2021-03-22 10:20
Hi @knowthelist, it's certainly possibly to add MQTT support!

I don't personally have a need for it and have not researched it before but I'm willing to look into it if you can help me understand what/how to. From what I've read in my brief search, it should be a relatively simple adaptation to the existing growatt_wifi.py script. What information are you hoping to extract from your inverter? Is there a specific "topic" (or set of topics) that should be published by the inverter?

After a quick search, I couldn't find an existing topic schema but I thought something like below may work; I'm not sure how the mains (AC1, AC2, AC3, Fac, Vac, etc.) topics would be best structured. I'm interested in your thoughts.

Thanks,
Aaron

```
home/solar/power/today      (Ppv)
home/solar/energy/today     (Eac Today)
home/solar/energy/total     (Eac Total)
home/solar/PV1/energy/today (Epv1 Today)
home/solar/PV1/energy/total (Epv1 Total)
home/solar/PV1/power        (Ppv1)
home/solar/PV1/current      (Ipv1)
home/solar/PV1/voltage      (Vpv1)
home/solar/PV2/energy/today (Epv2 Today)
home/solar/PV2/energy/total (Epv2 Total)
home/solar/PV2/power        (Ppv2)
home/solar/PV2/current      (Ipv2)
home/solar/PV2/voltage      (Vpv2)
```

**Comment by knowthelist** [comment] 2021-03-23 12:54
I don't use Pvoutput, even I don't know Pvoutput at all. 
I need to get the standard inverter data (Ppv, Epv, Eac, Eac total ...) into a home automation system (in my case FHEM) to store, aggregate and plot the pv parameter. I want to avoid cloud solutions at all costs.

MQTT seems for me to be a common solution for generic data exchange, but I didn't used it before. 
I'm also thinking about to re-implement the Growatt-server as a FHEM module in Perl. https://github.com/Tristan79/Growatt-WiFi-Tools/blob/master/scripts/growatt_server.pl is a good starting point, but the code is quite old and needs to be extended to support version 6 protocol.

**Comment by aaronjbrown** [comment] 2021-03-24 02:26
I'll look into publishing the EnergyRequest data with MQTT, most likely as a new "growatt_mqtt.py" script in the scripts/ directory, I just wanted to make sure I was on the right path before setting out. I'll use the schema above for now but it shouldn't be hard to amend in future.

**Comment by aaronjbrown** [comment] 2021-03-25 10:48
Hi, I've created an 'mqtt' branch with a lightly tested scripts/growatt_mqtt.py, updated requirements.txt and updated config.ini.example. Could you please checkout the mqtt branch, run ```pip install paho-mqtt```, then run growatt_mqtt.py?

Please let me know if the script does work for you as I will then merge it to master.

Thanks.

**Comment by knowthelist** [comment] 2021-03-29 09:42
Many thanks for your implementation. Generally, it works and I receive the MQTT messages, but all are empty:

current | 0 | 2021-03-29 10:49:00
frequency | 0 | 2021-03-29 10:49:00
power | 0 | 2021-03-29 10:49:00
status | 0 | 2021-03-29 10:48:59
today | 0 | 2021-03-29 10:49:00
total | 0 | 2021-03-29 10:49:00
voltage | 0 | 2021-03-29 10:49:00

After switching to DEBUG logging I saw a lot of unwanted GrowattBufferedEnergyRequests (0x50), but no one of the 5min interval GrowattEnergyRequests (0x04).

I guess there is an unexpected requests => response order or wrong content of the responses.
I get a lot of repeating GrowattAnnounceRequests and GrowattQueryResponse. Normally this will by sent only once after start.

assumption:
- Ping request needs just a ping reply with the serial (no query here)
- A first announcement needs a announcement reply with pack("C", 0x0) AND (followed) by a reply with a query request (0x19)
- all following announcements just a announcement reply with pack("C", 0x0))

**Comment by aaronjbrown** [comment] 2021-03-29 11:19
That sounds like the WiFi-X is not receiving the correct response. Are you able to see any responses being sent from the server back to the WiFi-X? For each packet received from the WiFi-X you should see the same information in the beginning of the packet, then a value of 0x47 (a 'G') at byte 62. The inverter stores the last ~30 days of data when it cannot connect to the server. When the connection restores, it sends this data every 30 seconds (as a GrowattBufferedEnergyRequest) in addition to the live data (as a GrowattEnergyRequest). If you're only receiving Ping, Query, and Buffered Energy packets from the inverter, I suspect the inverter is not receiving the correct ACK message.

Would you be comfortable sharing a wireshark/tcpdump capture of the traffic to/from your WiFi-X?

**Comment by openincident** [comment] 2021-05-02 05:13
I also would be very interested in this feature. I'd also like to post this to my local mqtt broker and have home assistant consume the data.

I've compiled the mqtt branch successfully, but I'm getting an error when I run it:
```
$ python3 ./growatt_mqtt.py 
Exception in thread ServerThread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/server/sync.py", line 620, in StartTcpServer
    server = ModbusTcpServer(context, framer, identity, address, **kwargs)
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/server/sync.py", line 338, in __init__
    socketserver.ThreadingTCPServer.__init__(self, self.address,
TypeError: __init__() got an unexpected keyword argument 'defer_reactor_run'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
TypeError: publish_data() missing 1 required positional argument: 'client'
`
```

I expect this is because I'm running on Ubuntu 20.04 and somehow my local env is broken, but I'm not sure how. I could use some help.

I would be able to provide a wireshark pretty easily. I'm getting data on port 5279 when I create a listener socket. Let me know how I can help.

**Comment by aaronjbrown** [comment] 2021-05-08 01:21
Hi @openincident, thanks for reaching out and offering to help!

I see you're running the script using Python 3. The initial module was written for Python 2 but I'm testing Python 3 in the ```python3``` branch. The python3 branch currently appears to respond to ```GrowattPingRequest``` and ```GrowattAnnounceRequest``` messages sent by the inverter, however from my testing the inverter is not sending through the ```GrowattEnergyRequest``` messages.

Are you able to save a copy of the ```growatt_mqtt.py``` script then checkout the ```python3``` branch and test the mqtt script with that?

If you're willing to install/test with python2 I'd be interested in your results with that also, but my preference is to get the python3 server functioning correctly.

Thanks!
Aaron

**Comment by openincident** [comment] 2021-05-15 02:38
Hi Aaron.
  
I started over with a fresh checkout, copied over the growatt_mqtt.py script and config.ini files, but I'm still getting a `"TypeError: __init__() got an unexpected keyword argument 'defer_reactor_run'"`, and it looks like the script is running, but after awhile I get a `"TypeError: publish_data() missing 1 required positional argument: 'client'" `and the script terminates.

I am seeing packets being sent and consumed on port 5279 though, I'll grab a wireshark capture and send it to you.

**Comment by aaronjbrown** [comment] 2021-05-28 10:02
I noticed the ```defer_reactor_run``` argument was incorrectly passed to a sync server and have removed it from the script. This is the cause of the ```"TypeError: __init__() got an unexpected keyword argument 'defer_reactor_run'"``` error.

I also missed passing the ```client``` parameter to the ```publish_data()``` function when it calls itself recursively on a timer, that was the cause of the  ```"TypeError: publish_data() missing 1 required positional argument: 'client'"``` error.

I also found a bug introduced when migrating the xor function to the ```growatt_framer``` class. The GrowattAnnounceResponse was sending a 0x00 response for ACK, rather than 0x47 (an  _xor'd_ 0x00). I'll test this tomorrow (sun has gone down for me) but I'm confident this is the cause of the inverter not sending any Energy data. I'll let you know how my testing goes before I ask you to test on the latest ```python3``` branch (now includes the patched ```growatt_mqtt.py``` script) - thank you for your help in debugging and your understanding of how side-projects can sometimes have slower turn-around times!

I guess I've found some gaps in my unit tests and end-to-end testing... Hopefully I've caught it all now and the python3 branch is stable; if so, I'll merge that to master.

I've also updated the README with information on how to install the Wireshark dissector I've been using for debugging.

**Comment by aaronjbrown** [comment] 2021-05-30 09:30
Hi @openincident, I've tested the latest ```python3``` branch over the past two day sand the ```growatt_pvoutput.py``` worked for me without issues (including resetting overnight). It looks like I found and fixed the bug causing the inverter to not send Energy data! I haven't been able to test the ```growatt_mqtt.py``` script too well because I don't have a personal MQTT broker/setup at home.

I've merged the ```python3``` branch to ```master```, so if you're able to checkout ```master``` and test again that would be great!

Thanks,
Aaron

**Comment by openincident** [comment] 2021-05-30 15:42
Hi @aaronjbrown  Great! I was testing your changes from 2 days ago when you did the merge. I just pulled master and restarted, and the only thing I can see from my Mosquitto logs is the script is only publishing 1 byte of data:

`1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/inverter/status', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV/power', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV/energy/total', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV1/voltage', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV1/current', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV1/power', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV1/energy/today', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV1/energy/total', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV2/voltage', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV2/current', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV2/power', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV2/energy/today', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/PV2/energy/total', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC/power', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC/frequency', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC1/voltage', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC1/current', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC1/power', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC/energy/today', ... (1 bytes))

1622388679: Received PUBLISH from Growatt MQTT (d0, q0, r0, m0, 'home/solar/AC/energy/total', ... (1 bytes))

`
Im not sure how the data could only be one byte, I'd expect the data is a double or a float, which should be at least 4 bytes, so I'm assuming it's wrong somehow. 

I'm using mosquitto from https://github.com/eclipse/mosquitto to test with. I have homeassistant listening to this server for messages from the various devices around the house.

Home assistant probably either requires or allows us to configure a certain format for the path and data, and that's my next task.

**Comment by aaronjbrown** [comment] 2021-06-01 10:32
When the script starts it publishes the current data, which at that point is all zero values. Does the script publish non-zero values each subsequent interval? This is not ideal and I've been thinking of writing a custom DataBlock ([like in this tutorial](https://pymodbus.readthedocs.io/en/latest/source/example/custom_datablock.html)) where the update to the DataBlock (the ```setValues``` method) is what triggers the MQTT publish.

The data will be the raw values reported by the inverter, which often need to be divided by 10 to shift the decimal point left one position (e.g. Vac will be reported as 2400 rather than 240.0V). Does Home Assistant allow you to configure this or should the conversion be performed before publishing? I don't know if there's a standard for publishing data on MQTT but I'd like to follow it if there is.

**Comment by openincident** [comment] 2021-06-04 16:54
So I've let the script run overnight, and I always get zeros. However, I also did get several segfaults after a period: 


`2021-06-04 00:58:47,744 ERROR    sync:handle(211) Socket exception occurred Traceback (most recent call last):
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/server/sync.py", line 201, in handle
    self.framer.processIncomingPacket(data, self.execute, units,
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
    self._process(callback)
  File "/home/dzubey/.local/lib/python3.8/site-packages/PyGrowatt/growatt_framer.py", line 59, in _process
    result = self.decoder.decode(data)
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/factory.py", line 104, in decode
    return self._helper(message)
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/factory.py", line 138, in _helper
    request.decode(data[1:])
  File "/home/dzubey/.local/lib/python3.8/site-packages/PyGrowatt/Growatt.py", line 492, in decode
    self.config_id, self.config_length = struct.unpack_from('>HH', data, 30)
struct.error: unpack_from requires a buffer of at least 34 bytes for unpacking 4 bytes at offset 30 (actual buffer size is 15)
`
as well as one of these:

`2021-06-04 00:58:55,462 ERROR    sync:handle(211) Socket exception occurred Traceback (most recent call last):
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/server/sync.py", line 201, in handle
    self.framer.processIncomingPacket(data, self.execute, units,
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
    self._process(callback)
  File "/home/dzubey/.local/lib/python3.8/site-packages/PyGrowatt/growatt_framer.py", line 59, in _process
    result = self.decoder.decode(data)
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/factory.py", line 104, in decode
    return self._helper(message)
  File "/home/dzubey/.local/lib/python3.8/site-packages/pymodbus/factory.py", line 138, in _helper
    request.decode(data[1:])
  File "/home/dzubey/.local/lib/python3.8/site-packages/PyGrowatt/Growatt.py", line 493, in decode
    self.config_value = struct.unpack_from(">" + str(self.config_length) + "s", data, 34)[0]
struct.error: unpack_from requires a buffer of at least 12186 bytes for unpacking 12152 bytes at offset 34 (actual buffer size is 43)
`

As for the MQTT data format, it depends on the application. For Home Assistant, this is relevant [here](https://www.home-assistant.io/docs/mqtt/discovery/). Basically there needs to exist a configuration call to set the exepected endpoint inside of home assistant, and then it's a json string that's posted. 

For the raw value, yea, probably shift it before publishing it, as the topic you're posting to indicates volts.

**Comment by aaronjbrown** [comment] 2021-06-09 10:53
That's strange that you're getting all zero's. You've mentioned that you've run Wireshark, do you by chance have a recent recording? I'm curious to know if you're getting any Energy packets from the inverter. If you're able to install the Wireshark dissector (notes in the README.md) could you please filter on ```growatt.fc == "Energy"``` (or ```growatt.fc == 0x04```) to confirm you're receiving packets?

Those two errors appear to be malformed Query Requests. Do you have packet captures of these?

Good point on the values being published, that makes perfect sense! I'll start working on that, thanks!

**Comment by openincident** [comment] 2021-06-14 00:10
Okay, I've included the capture file. Let me know and shoot me your email if github shreds the file as I've named it a text file and it's really a binary.
[growattcapture.txt](https://github.com/aaronjbrown/PyGrowatt/files/6644889/growattcapture.txt)

I'll also research the correct json format to send to the mqtt server and respond back shortly. 

Thank you Aaron.

**Comment by aaronjbrown** [comment] 2021-06-18 11:11
Ah, it looks like your WiFi-X is using a different version of the protocol! The Wireshark dissector is showing Protocol ID 5, and the WiFi Serial is only 10 bytes long, not the 30 bytes I'm seeing on mine with Protocol ID 6. This has broken the Wireshark dissector too... I created a new ```pid5``` branch and updated dissector and first attempt at processing for your version protocol. I think it might take a bit of debugging (and back-and-forth) to find all the nuances between our two versions of the protocol.

The protocol version difference means that PyGrowatt isn't responding to the inverter's Pings correctly and the inverter is therefore not sending the Energy data. I think the sequence should be:
1. Inverter sends Ping
2. Server sends Ping (as ACK)
3. Inverter sends Announce
4. Server sends Announce ACK
5. Inverter sends Energy data
6. Server sends Energy ACK

**Comment by aaronjbrown** [comment] 2022-01-22 02:54
I have tested the pygrowatt_mqtt.py script to work and have configured the Docker image to run MQTT by default (refer commit ac8d88257c146750e4a2703ec0bf05538e991dda).

Closing this Feature Request.

**Closed as completed by aaronjbrown** 2022-01-22 02:54 UTC

**Comment by openincident** [comment] 2022-01-22 03:29
Thank you for your time. I've had to repair my growatt, when I get it
online I'll retest, as this is still needed.

**Comment by aaronjbrown** [comment] 2022-01-25 07:20
Hi @openincident, you'll likely still have Protocol ID 5 v 6 compatibility issues. Let me look into merging master (which has the MQTT support) with the PID 5 branch for you.
